### ISSUE TITLE
Adding CodeCov and Travis CI build

### ISSUE THREAD

**Issue by nguyenkatie1** [TrainingGithub/Training#3]

**Comment by nguyenkatie1** [comment]
[![Build Status](https://travis-ci.org/TrainingGithub/Training.svg?branch=master)](https://travis-ci.org/TrainingGithub/Training)

**Comment by katydid98** [comment]
[![Build Status](https://travis-ci.org/TrainingGithub/Training.svg?branch=master)](https://travis-ci.org/TrainingGithub/Training)

**Comment by nguyenkatie1** [comment]
[![codecov](https://codecov.io/gh/katydid98/Training/branch/master/graph/badge.svg)](https://codecov.io/gh/katydid98/Training)
